//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWPappPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BADANIE
    {
        public Nullable<System.DateTime> DATA_BADANIA { get; set; }
        public string RODZAJ { get; set; }
        public string WYNIK { get; set; }
        public int BADANIE_ID { get; set; }
        public Nullable<int> KARTA_PACJENTA_ID { get; set; }
        public Nullable<int> LEKARZ_ZLECAJACY { get; set; }
    
        public virtual KARTA_PACJENTA KARTA_PACJENTA { get; set; }
        public virtual LEKARZ LEKARZ { get; set; }
    }
}
