//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWPappPro.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class OPINIA
    {
        public int OPINIA_ID { get; set; }
        public Nullable<int> NUMER_OPINII { get; set; }
        [Required]
        public string TRESC { get; set; }
        [Required]
        [RegularExpression("^([0-9]|10)$", ErrorMessage = "Zakres ocen to: 0 - 10")]
        public Nullable<int> OCENA { get; set; }
        public Nullable<int> LEKARZ_ID { get; set; }
        public Nullable<int> PACJENT_ID { get; set; }
    
        public virtual LEKARZ LEKARZ { get; set; }
        public virtual PACJENT PACJENT { get; set; }
    }
}
