//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWPappPro.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;

    public partial class PACJENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACJENT()
        {
            this.KARTA_PACJENTA = new HashSet<KARTA_PACJENTA>();
            this.KONSULTACJA_ONLINE = new HashSet<KONSULTACJA_ONLINE>();
            this.OPINIA = new HashSet<OPINIA>();
            this.POWIADOMIENIE = new HashSet<POWIADOMIENIE>();
            this.WIZYTA_DOMOWA = new HashSet<WIZYTA_DOMOWA>();
            this.WIZYTA_KONSULTACYJNA = new HashSet<WIZYTA_KONSULTACYJNA>();
        }
    
        public int PACJENT_ID { get; set; }
        public string IMIE { get; set; }
        public string NAZWISKO { get; set; }
        public string PESEL { get; set; }
        public Nullable<System.DateTime> DATA_URODZENIA { get; set; }
        public string MIEJSCE_URODZENIA { get; set; }
        public string ULICA_ZAMIESZKANIA { get; set; }
        public string MIEJSCOWOSC { get; set; }
        public string KOD_POCZTOWY { get; set; }
        public string ADRES_E_MAIL { get; set; }
        public string NR_TELEFONU { get; set; }
        public string HASLO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KARTA_PACJENTA> KARTA_PACJENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KONSULTACJA_ONLINE> KONSULTACJA_ONLINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPINIA> OPINIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POWIADOMIENIE> POWIADOMIENIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WIZYTA_DOMOWA> WIZYTA_DOMOWA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WIZYTA_KONSULTACYJNA> WIZYTA_KONSULTACYJNA { get; set; }

        public bool ZalogujPacjent(PACJENT entity, HttpContextBase current)
        {

            var db = new SWPappDBEntities4();
            //pobranie z bazy danych rekordu o nazwie uzytkownika takiej jak podanej w entity(czyli danych z formularza)
            var pass = db.PACJENT.Where(s => s.PESEL == entity.PESEL.Trim()).FirstOrDefault();
            //jesli rekord istnieje
            if (pass != null)
            {
                //porównanie hase³
                if (entity.HASLO.Equals(pass.HASLO.Trim()))
                {
                    current.Session["typ"] = "pacjent";
                    current.Session["login"] = pass.PESEL;
                    current.Session["id"] = pass.PACJENT_ID;
                    return true;

                }
                return false;
            }
            else
            {
                return false;
            }

        }


    }
}
