//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWPappPro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SWPappDBEntities4 : DbContext
    {
        public SWPappDBEntities4()
            : base("name=SWPappDBEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BADANIE> BADANIE { get; set; }
        public virtual DbSet<GABINET> GABINET { get; set; }
        public virtual DbSet<KARTA_PACJENTA> KARTA_PACJENTA { get; set; }
        public virtual DbSet<KONSULTACJA_ONLINE> KONSULTACJA_ONLINE { get; set; }
        public virtual DbSet<KONSULTANT> KONSULTANT { get; set; }
        public virtual DbSet<LEKARZ> LEKARZ { get; set; }
        public virtual DbSet<OPINIA> OPINIA { get; set; }
        public virtual DbSet<PACJENT> PACJENT { get; set; }
        public virtual DbSet<POWIADOMIENIE> POWIADOMIENIE { get; set; }
        public virtual DbSet<TERMINARZ> TERMINARZ { get; set; }
        public virtual DbSet<WIZYTA_DOMOWA> WIZYTA_DOMOWA { get; set; }
        public virtual DbSet<WIZYTA_KONSULTACYJNA> WIZYTA_KONSULTACYJNA { get; set; }
    }
}
