//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWPappPro.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    /// <summary>
    /// Przyk³adowa klasa danych utworzona przy pomocy EntityFramework bêd¹ca obiektem zmapowanym na encje.
    /// </summary>
    public partial class users
    {
        /// <summary>
        /// Nazwa uzytkownika
        /// </summary>
        public string username { get; set; }
        /// <summary>
        /// Has³o uzytkownika
        /// </summary>
        public string password { get; set; }
        /// <summary>
        /// Typ konta uzytkownika
        /// </summary>
        public string type { get; set; }

    /// <summary>
    /// Metoda porównuj¹ca parametry obiektu wejsciowego (entity) z pobranym z tablicy users.
    /// Po porównaniu hase³ u¿ytkowników zwracany jest odpowiednia wartoœæ True lub False.
    /// </summary>
    /// <param name="entity"></param>
    /// <param name="current"></param>
    /// <returns>True, jeœli u¿ytkownik istnieje i has³a siê zgadzaj¹, False w przeciwnym razie.</returns>
    public bool ValidateUser(users entity, HttpContextBase current)
        {

            var db = new SWPappDBEntities5();
            //pobranie z bazy danych rekordu o nazwie uzytkownika takiej jak podanej w entity(czyli danych z formularza)
            var pass = db.users.Where(s => s.username == entity.username.Trim()).FirstOrDefault();
            //jesli rekord istnieje
            if (pass != null)
            {
                //porównanie hase³
                if (entity.password.Equals(pass.password.Trim()))
                {
                    //ustawienie odpowiednich zmiennych sesji
                    if (pass.type.Trim().Equals("lekarz"))
                    {
                        current.Session["typ"] = "lekarz";
                    }
                    else
                    {
                        current.Session["typ"] = "pacjent";
                    }
                    current.Session["login"] = pass.username;
                    return true;
                }
                return false;
            }
            else
            {
                return false;
            }  
        }
    }

}
